version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres_source
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: source_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_source
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Developer"
      MSSQL_MEMORY_LIMIT_MB: "2048"
    deploy:
      resources:
        limits:
          memory: 2g
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

networks:
  default:
    name: kind
    external: true

volumes:
  postgres_data:
  mssql_data: